name: workflows

on:
  pull_request:
  schedule:
    - cron: '0 11 * * *' # Run nightly at 11am UTC (3am Pacific, 6am Eastern)

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:

  ktfmtCheck:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/checkout@v3
      - run: ./gradlew ktfmtCheck

  assembleDebug:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew assembleDebug

  tsc:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: AppCheckServer/package-lock.json
      - run: npm clean-install
        working-directory: AppCheckServer
      - run: npm run tsc
        working-directory: AppCheckServer

  prettier:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: AppCheckServer/package-lock.json
      - run: npm clean-install
        working-directory: AppCheckServer
      - run: npm run prettier:check
        working-directory: AppCheckServer

  eslint:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: AppCheckServer/package-lock.json
      - run: npm clean-install
        working-directory: AppCheckServer
      - run: npm run lint:check
        working-directory: AppCheckServer
